name: qvim # you probably want to 'snapcraft register <name>'
version: 'dev' # just for humans, typically '1.2+git' or '1.3.2'
summary: Qt interface for vim
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  vim:
    command: usr/bin/vim

  qvim:
    command: usr/bin/qvim

parts:
  prepare-qt5:
    plugin: nil
    after: [qt5conf, desktop-qt5]
    prepare: |
      apt install -y qt5-default

  vim-qt:
    plugin: autotools
    source: https://github.com/equalsraf/vim-qt.git
    source-depth: 1
    after: [prepare-qt5]
    #stage-packages: [libqt5gui5]
    build-packages:
      - python-dev
      - python3-dev
      - libpython-dev
      - libpython3.5-dev
      - liblua5.2-dev
      - luajit
      - libluajit-5.1-dev
      - qt5-default

    configflags:
      - --enable-multibyte
      - --enable-pythoninterp=dynamic
      - --enable-python3interp
      - --enable-cscope
      - --enable-gui=qt
      - --with-features=huge
      - --with-x
      - --enable-largefile
      - --disable-netbeans
      - --enable-fail-if-missing
      - --prefix=/usr

  make-links:
    plugin: nil
    after: [vim-qt]
    install: |
      ln $SNAPCRAFT_STAGE/usr/bin/vim $SNAPCRAFT_STAGE/usr/bin/qvim
    prime:
      - usr/bin/qvim




